//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dmlm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactItem
    {
        public int Id { get; set; }
        public string email { get; set; }
        public string phoneNumber { get; set; }
        public string cellPhoneNumber { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string address3 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string postalCode { get; set; }
        public Nullable<System.TimeSpan> workingHoursStartTime { get; set; }
        public Nullable<System.TimeSpan> workingHoursEndTime { get; set; }
        public int contactId { get; set; }
        public Nullable<bool> preferredContactEmail { get; set; }
        public Nullable<bool> prefrredContactCell { get; set; }
        public Nullable<bool> preferredContactPhone { get; set; }
    
        public virtual Contact Contact { get; set; }
    }
}
