//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dmlm
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryCount
    {
        public int Id { get; set; }
        public Nullable<double> count { get; set; }
        public int productId { get; set; }
        public int inventoryLocationId { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public int userId { get; set; }
        public int uomId { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual InventoryLocation InventoryLocation { get; set; }
        public virtual UOM UOM { get; set; }
    }
}
