//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dmlm
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationContact
    {
        public int Id { get; set; }
        public int locationId { get; set; }
        public int contactId { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> isPrimaryContact { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual Location Location { get; set; }
    }
}
