//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dmlm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Location()
        {
            this.LocationContacts = new HashSet<LocationContact>();
            this.InventoryLocations = new HashSet<InventoryLocation>();
            this.RegionLocations = new HashSet<RegionLocation>();
            this.LocationHours = new HashSet<LocationHour>();
            this.LocationClosedDates = new HashSet<LocationClosedDate>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string address3 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string postalCode { get; set; }
        public string county { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> radius { get; set; }
        public string zoneDescription { get; set; }
        public string googleMapSmall { get; set; }
        public string googleMapMedium { get; set; }
        public string url { get; set; }
        public string imageUrl { get; set; }
        public Nullable<System.TimeSpan> operatingHoursStart { get; set; }
        public Nullable<System.TimeSpan> operatingHoursEnd { get; set; }
        public string operatingDays { get; set; }
        public int serviceProviderId { get; set; }
        public int locationCategoryId { get; set; }
        public string phone { get; set; }
        public Nullable<double> longitude { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationContact> LocationContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryLocation> InventoryLocations { get; set; }
        public virtual LocationCategory LocationCategory { get; set; }
        public virtual ServiceProvider ServiceProvider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegionLocation> RegionLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationHour> LocationHours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationClosedDate> LocationClosedDates { get; set; }
    }
}
