//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dmlm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dmlmEntities : DbContext
    {
        public dmlmEntities()
            : base("name=dmlmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<ContactItem> ContactItems { get; set; }
        public virtual DbSet<DefaultUOM> DefaultUOMs { get; set; }
        public virtual DbSet<InventoryCount> InventoryCounts { get; set; }
        public virtual DbSet<InventoryLocation> InventoryLocations { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<LocationCategory> LocationCategories { get; set; }
        public virtual DbSet<LocationContact> LocationContacts { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductCategory> ProductCategories { get; set; }
        public virtual DbSet<ProductInventoryLocation> ProductInventoryLocations { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<RegionLocation> RegionLocations { get; set; }
        public virtual DbSet<RegionUser> RegionUsers { get; set; }
        public virtual DbSet<ServiceProvider> ServiceProviders { get; set; }
        public virtual DbSet<Territory> Territories { get; set; }
        public virtual DbSet<UOM> UOMs { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Manufacturer> Manufacturers { get; set; }
        public virtual DbSet<Alert> Alerts { get; set; }
        public virtual DbSet<LocationClosedDate> LocationClosedDates { get; set; }
        public virtual DbSet<LocationHour> LocationHours { get; set; }
        public virtual DbSet<UserAlert> UserAlerts { get; set; }
        public virtual DbSet<UserDevice> UserDevices { get; set; }
    }
}
