//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dmlm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceProviderWidgetRole
    {
        public int Id { get; set; }
        public int ServiceProviderWidgetID { get; set; }
        public int RoleID { get; set; }
    
        public virtual ServiceProviderWidget ServiceProviderWidget { get; set; }
        public virtual Role Role { get; set; }
    }
}
