//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dmlm
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string title { get; set; }
        public string employeeNumber { get; set; }
        public string emailAddress { get; set; }
        public string phoneNumber { get; set; }
        public Nullable<bool> cellPhoneNumber { get; set; }
        public string isActive { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public int serviceProviderId { get; set; }
    }
}
