//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dmlm
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAlert
    {
        public int Id { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> alertID { get; set; }
    
        public virtual User User { get; set; }
        public virtual Alert Alert { get; set; }
    }
}
